CREATE EVENT MODIF_DOSSIER 
ON SCHEDULE EVERY 1 WEEK STARTS '2015-12-09 12:41:56' 
ON COMPLETION NOT PRESERVE DISABLE DO 
UPDATE dossier SET ETAT='en_attente_commission' WHERE ETAT='traité_secretariat_formation';

